platform :ios, "8.0"

target '趣味信息分享' do

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "DACircularProgress"
pod "pop"
pod "NJKWebViewProgress"
pod "FreeStreamer"

end